spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: katmabahuarwa
    url: jdbc:mysql://localhost:3306/boot9am
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
